### PR TITLE
Mike's changes for march 2

### PR DESCRIPTION
**Pull request by EmoCthulhu**
Basically retroffiting all EmoCthulhu templates to take advantage of all the wonderful new features and special keywords.

### CODE REVIEW

**Review by EmoCthulhu — COMMENTED** [review]
I need to dump this commit. The Update settings .json. Don't know how that snuck in there.

**Comment by EddieDover** [comment]
Yeah. I added a spellchecking plugin, then removed it because it was a hassle and a half to retroactively maintain.

**Review by EddieDover — COMMENTED** [review]
Looks good so far. We'll prep the merge after #66 goes in.

**Comment by EmoCthulhu** [comment]
Yeah I still need to do Alien, TWD and Blade Runner after physio. Shouldn't take long. Might as well get s0, s, s# and u into those. Won't be finishing pf1 this week. Kinda hoping that the person in #general will take the new release and run with it, the more people that contribute, the better.

**Review by EddieDover — APPROVED** [review]

**Pull request merged**
