### PR TITLE
Added vtm5e files

### PR DESCRIPTION
**Pull request by pmenezesdev**
Two files one for portuguese and other to english speakers

### CODE REVIEW

**Comment by EddieDover** [comment]
Is there any chance you'd be willing to include images and add these to the TEMPLATE_LIST.md?

**Comment by pmenezesdev** [comment]
For sure!

**Comment by pmenezesdev** [comment]
Done!

**Comment by EddieDover** [comment]
Thanks for the contribution!!

**Review by EddieDover — APPROVED** [review]

**Pull request merged**
